<?php


/**
 * This class adds structure of 'spy_form_builder_action' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 03/10/09 10:37:16
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.spyFormBuilderInterface2Plugin.lib.model.map
 */
class SpyFormBuilderActionMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.spyFormBuilderInterface2Plugin.lib.model.map.SpyFormBuilderActionMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(SpyFormBuilderActionPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(SpyFormBuilderActionPeer::TABLE_NAME);
		$tMap->setPhpName('SpyFormBuilderAction');
		$tMap->setClassname('SpyFormBuilderAction');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('ACTION_TYPE', 'ActionType', 'VARCHAR', true, 255);

		$tMap->addColumn('ACTION_PARAMS', 'ActionParams', 'LONGVARCHAR', false, null);

		$tMap->addForeignKey('FORM_ID', 'FormId', 'INTEGER', 'spy_form_builder', 'ID', true, null);

		$tMap->addColumn('RANK', 'Rank', 'INTEGER', false, null);

	} // doBuild()

} // SpyFormBuilderActionMapBuilder
