all:
  actions:
    actions:
      store_propel:
        generateYml:
          title: Générate the YML
          img: /sf/sf_admin/images/default_icon.png
    post:
      send_mail:
        name: Send an Email
        type: spyActionSendMail
        params:
          options:
            to:
             name: Destinator of the mail
             type: sfWidgetFormInput
             attributes:
               size: 30
             validators:
               email:
                 class: sfValidatorEmail
                 messages:
                   invalid: You must set a valid email
            from:
             name: From Email
             type: sfWidgetFormInput 
             attributes:
              size: 30
             validators:
              email:
                class: sfValidatorEmail
                messages:
                  invalid: You must set a valid email 
            subject:
             name: Email Subject
             type: sfWidgetFormInput 
             attributes:
              size: 55
      store_propel:
        name: Store In propel Database
        type: spyActionStoreInPropel
        params:
          options:
            dbname:
              name: Name of The database
              type: sfWidgetFormInput
              attributes:
                size: 30
              options:
                default: propel
            table_name:
              name: Name of The table
              type: sfWidgetFormInput
              attributes:
                size: 30